from backend.data_access.database.database_interactors.database_helpers.create_db import create_database_framework
from backend.data_access.database.database_interactors.database_helpers.fetch_db import fetch_all_data
from backend.data_access.database.database_interactors.database_helpers.populate_db import populate_database
from backend.scraper.competition_information import get_competition_information

create_database_framework()
competition_data = get_competition_information()
populate_database(competition_data)
fetch_all_data()
